const path = require('path');

const flags = ['--headless=new'];
if (process.env.CI) {
  flags.push('--no-sandbox');
}

module.exports = async function (karma) {
  karma.set({
    hostname: '127.0.0.1',
    browsers: ['ChromeHeadless'],
    customLaunchers: {
      ChromeHeadless: {
        base: 'Chrome',
        flags,
      },
    },
    browserDisconnectTolerance: 2,
    frameworks: ['webpack', 'mocha', 'source-map-support'],
    client: {
      runInParent: true,
      mocha: {
        timeout: 2500,
      },
    },
    files: [
      {
        pattern: path.resolve(__dirname, './test-extensions.js'),
      },
      {
        pattern: 'spec/**/*.test.js',
        watched: false,
      },
      {
        pattern: '**/*',
        included: false,
        watched: false,
      },
    ],
    // Specs ported to Vitest run there instead; see test/browser/vitest.config.mjs.
    exclude: [
      'spec/ol/DataTile.test.js',
      'spec/ol/Map.test.js',
      'spec/ol/MapBrowserEvent.test.js',
      'spec/ol/MapBrowserEventHandler.test.js',
      'spec/ol/Tile.test.js',
      'spec/ol/View.test.js',
      'spec/ol/color.test.js',
      'spec/ol/colorlike.test.js',
      'spec/ol/control/attribution.test.js',
      'spec/ol/control/control.test.js',
      'spec/ol/control/fullscreen.test.js',
      'spec/ol/control/mouseposition.test.js',
      'spec/ol/control/overviewmap.test.js',
      'spec/ol/control/rotate.test.js',
      'spec/ol/control/zoom.test.js',
      'spec/ol/control/scaleline.test.js',
      'spec/ol/control/zoomslider.test.js',
      'spec/ol/control/zoomtoextent.test.js',
      'spec/ol/dom/dom.test.js',
      'spec/ol/expr/cpu.test.js',
      'spec/ol/expr/expression.test.js',
      'spec/ol/expr/gpu.test.js',
      'spec/ol/featureloader.test.js',
      'spec/ol/format/gml.test.js',
      'spec/ol/format/gpx.test.js',
      'spec/ol/format/igc.test.js',
      'spec/ol/format/iiif.test.js',
      'spec/ol/format/kml.test.js',
      'spec/ol/format/mvt.test.js',
      'spec/ol/format/osmxml.test.js',
      'spec/ol/format/ows.test.js',
      'spec/ol/format/wfs.test.js',
      'spec/ol/format/wmscapabilities.test.js',
      'spec/ol/format/wmsgetfeatureinfo.test.js',
      'spec/ol/format/wmtscapabilities.test.js',
      'spec/ol/format/xsd.test.js',
      'spec/ol/geolocation.test.js',
      'spec/ol/graticule.test.js',
      'spec/ol/image.test.js',
      'spec/ol/imagetile.test.js',
      'spec/ol/net.test.js',
      'spec/ol/interaction/DragBox.test.js',
      'spec/ol/interaction/Draw.test.js',
      'spec/ol/interaction/Pointer.test.js',
      'spec/ol/interaction/dblclickdragzoom.test.js',
      'spec/ol/interaction/draganddrop.test.js',
      'spec/ol/interaction/dragrotateandzoom.test.js',
      'spec/ol/interaction/interaction.test.js',
      'spec/ol/interaction/extent.test.js',
      'spec/ol/interaction/dragzoom.test.js',
      'spec/ol/interaction/modify.test.js',
      'spec/ol/interaction/keyboardpan.test.js',
      'spec/ol/interaction/keyboardzoom.test.js',
      'spec/ol/interaction/mousewheelzoom.test.js',
      'spec/ol/interaction/select.test.js',
      'spec/ol/interaction/snap.test.js',
      'spec/ol/interaction/translate.test.js',
      'spec/ol/layer/Flow.test.js',
      'spec/ol/layer/Group.test.js',
      'spec/ol/layer/Heatmap.test.js',
      'spec/ol/layer/WebGLTile.test.js',
      'spec/ol/layer/WebGLVector.test.js',
      'spec/ol/layer/WebGLVectorTile.test.js',
      'spec/ol/layer/Image.test.js',
      'spec/ol/layer/Layer.test.js',
      'spec/ol/layer/Tile.test.js',
      'spec/ol/layer/Vector.test.js',
      'spec/ol/layer/vectorimage.test.js',
      'spec/ol/layer/vectortile.test.js',
      'spec/ol/loadingstrategy.test.js',
      'spec/ol/overlay.test.js',
      'spec/ol/proj/epsg3857.test.js',
      'spec/ol/proj/transforms.test.js',
      'spec/ol/render.test.js',
      'spec/ol/render/box.test.js',
      'spec/ol/render/canvas/executorgroup.test.js',
      'spec/ol/render/canvas/index.test.js',
      'spec/ol/render/canvas/hitdetect.test.js',
      'spec/ol/render/canvas/immediate.test.js',
      'spec/ol/render/canvas/style.test.js',
      'spec/ol/render/canvas/textbuilder.test.js',
      'spec/ol/render/canvas/zindexcontext.test.js',
      'spec/ol/render/feature.test.js',
      'spec/ol/render/webgl/MixedGeometryBatch.test.js',
      'spec/ol/render/webgl/VectorStyleRenderer.test.js',
      'spec/ol/render/webgl/bufferUtil.test.js',
      'spec/ol/render/webgl/compileUtil.test.js',
      'spec/ol/render/webgl/renderinstructions.test.js',
      'spec/ol/render/webgl/encodeUtil.test.js',
      'spec/ol/render/webgl/shaderbuilder.test.js',
      'spec/ol/render/webgl/style.test.js',
      'spec/ol/renderer/canvas/ImageLayer.test.js',
      'spec/ol/renderer/canvas/Layer.test.js',
      'spec/ol/renderer/canvas/TileLayer.test.js',
      'spec/ol/renderer/canvas/VectorLayer.test.js',
      'spec/ol/renderer/canvas/builder.test.js',
      'spec/ol/renderer/canvas/vectorimage.test.js',
      'spec/ol/renderer/canvas/vectortilelayer.test.js',
      'spec/ol/renderer/layer.test.js',
      'spec/ol/renderer/vector.test.js',
      'spec/ol/renderer/webgl/Layer.test.js',
      'spec/ol/renderer/webgl/PointsLayer.test.js',
      'spec/ol/renderer/webgl/VectorLayer.test.js',
      'spec/ol/renderer/webgl/VectorTileLayer.test.js',
      'spec/ol/renderer/webgl/TileLayer.test.js',
      'spec/ol/reproj/image.test.js',
      'spec/ol/reproj/reproj.test.js',
      'spec/ol/reproj/tile.test.js',
      'spec/ol/reproj/triangulation.test.js',
      'spec/ol/resolutionconstraint.test.js',
      'spec/ol/rotationconstraint.test.js',
      'spec/ol/size.test.js',
      'spec/ol/source.test.js',
      'spec/ol/source/BingMaps.test.js',
      'spec/ol/source/DataTile.test.js',
      'spec/ol/source/GeoZarr.test.js',
      'spec/ol/source/IIIF.test.js',
      'spec/ol/source/Image.test.js',
      'spec/ol/source/ImageArcGISRest.test.js',
      'spec/ol/source/ImageWMS.test.js',
      'spec/ol/source/ImageMapGuide.test.js',
      'spec/ol/source/ImageStatic.test.js',
      'spec/ol/source/OGCMap.test.js',
      'spec/ol/source/Source.test.js',
      'spec/ol/source/StadiaMaps.test.js',
      'spec/ol/source/Tile.test.js',
      'spec/ol/source/TileArcGISRest.test.js',
      'spec/ol/source/TileImage.test.js',
      'spec/ol/source/TileJSON.test.js',
      'spec/ol/source/TileWMS.test.js',
      'spec/ol/source/UrlTile.test.js',
      'spec/ol/source/VectorTile.test.js',
      'spec/ol/source/WMTS.test.js',
      'spec/ol/source/XYZ.test.js',
      'spec/ol/source/Zoomify.test.js',
      'spec/ol/source/cartodb.test.js',
      'spec/ol/source/cluster.test.js',
      'spec/ol/source/mapserver.test.js',
      'spec/ol/source/raster.test.js',
      'spec/ol/source/utfgrid.test.js',
      'spec/ol/source/vector.test.js',
      'spec/ol/sphere.test.js',
      'spec/ol/string.test.js',
      'spec/ol/style/Circle.test.js',
      'spec/ol/style/RegularShape.test.js',
      'spec/ol/style/fill.test.js',
      'spec/ol/style/icon.test.js',
      'spec/ol/style/iconimagecache.test.js',
      'spec/ol/style/stroke.test.js',
      'spec/ol/style/style.test.js',
      'spec/ol/style/text.test.js',
      'spec/ol/tilecoord.test.js',
      'spec/ol/tilegrid/wmts.test.js',
      'spec/ol/tilequeue.test.js',
      'spec/ol/tilerange.test.js',
      'spec/ol/tileurlfunction.test.js',
      'spec/ol/transform.test.js',
      'spec/ol/uri.test.js',
      'spec/ol/vectorrendertile.test.js',
      'spec/ol/vectortile.test.js',
      'spec/ol/webgl/TileGeometry.test.js',
      'spec/ol/webgl/TileTexture.test.js',
      'spec/ol/webgl/buffer.test.js',
      'spec/ol/webgl/helper.test.js',
      'spec/ol/webgl/rendertarget.test.js',
      'spec/ol/worker/webgl.test.js',
    ],
    proxies: {
      '/spec/': '/base/spec/',
      '/wms': '/base/spec/ol/data/blank.png',
      '/ogcapi/map': '/base/spec/ol/data/blank.png',
      '/ImageServer/exportImage': '/base/spec/ol/data/blank.png',
      '/MapServer/export': '/base/spec/ol/data/blank.png',
    },
    preprocessors: {
      '**/*.js': ['webpack'], //, 'sourcemap'],
    },
    reporters: ['dots'],
    webpack: {
      devtool: 'inline-source-map',
      mode: 'development',
      resolve: {
        alias: {
          ol: path.resolve(__dirname, '../../src/ol/'),
        },
        fallback: {
          fs: false,
          http: false,
          https: false,
        },
      },
      module: {
        rules: [
          {
            test: /\.js$/,
            enforce: 'pre',
            use: ['source-map-loader'],
          },
          {
            test: /\.js$/,
            use: {
              loader: path.join(
                __dirname,
                '../../examples/webpack/worker-loader.cjs',
              ),
            },
            include: [path.join(__dirname, '../../src/ol/worker')],
          },
        ],
      },
    },
    webpackMiddleware: {
      noInfo: true,
    },
  });

  process.env.CHROME_BIN = await require('puppeteer').executablePath();
};
