import {playwright} from '@vitest/browser-playwright';
import path from 'path';
import {fileURLToPath} from 'url';
import {defineConfig} from 'vitest/config';
import olFixtures from './vite-plugin-ol-fixtures.mjs';
import olWorker from './vite-plugin-ol-worker.mjs';

const dir = path.dirname(fileURLToPath(import.meta.url));

// Runs a few representative specs while the migration off Karma is in progress.
export default defineConfig({
  plugins: [olWorker(), olFixtures()],
  test: {
    include: [
      'test/browser/spec/ol/MapBrowserEvent.test.js',
      'test/browser/spec/ol/Tile.test.js',
      'test/browser/spec/ol/color.test.js',
      'test/browser/spec/ol/colorlike.test.js',
      'test/browser/spec/ol/control/fullscreen.test.js',
      'test/browser/spec/ol/control/mouseposition.test.js',
      'test/browser/spec/ol/control/overviewmap.test.js',
      'test/browser/spec/ol/control/rotate.test.js',
      'test/browser/spec/ol/control/zoom.test.js',
      'test/browser/spec/ol/control/zoomslider.test.js',
      'test/browser/spec/ol/control/zoomtoextent.test.js',
      'test/browser/spec/ol/dom/dom.test.js',
      'test/browser/spec/ol/expr/cpu.test.js',
      'test/browser/spec/ol/expr/expression.test.js',
      'test/browser/spec/ol/expr/gpu.test.js',
      'test/browser/spec/ol/featureloader.test.js',
      'test/browser/spec/ol/format/gpx.test.js',
      'test/browser/spec/ol/format/igc.test.js',
      'test/browser/spec/ol/format/iiif.test.js',
      'test/browser/spec/ol/format/osmxml.test.js',
      'test/browser/spec/ol/format/ows.test.js',
      'test/browser/spec/ol/format/wmtscapabilities.test.js',
      'test/browser/spec/ol/format/xsd.test.js',
      'test/browser/spec/ol/geolocation.test.js',
      'test/browser/spec/ol/graticule.test.js',
      'test/browser/spec/ol/interaction/Pointer.test.js',
      'test/browser/spec/ol/layer/Flow.test.js',
      'test/browser/spec/ol/layer/Heatmap.test.js',
      'test/browser/spec/ol/loadingstrategy.test.js',
      'test/browser/spec/ol/overlay.test.js',
      'test/browser/spec/ol/proj/epsg3857.test.js',
      'test/browser/spec/ol/proj/transforms.test.js',
      'test/browser/spec/ol/render.test.js',
      'test/browser/spec/ol/render/box.test.js',
      'test/browser/spec/ol/render/canvas/executorgroup.test.js',
      'test/browser/spec/ol/render/canvas/hitdetect.test.js',
      'test/browser/spec/ol/render/canvas/style.test.js',
      'test/browser/spec/ol/render/canvas/zindexcontext.test.js',
      'test/browser/spec/ol/render/feature.test.js',
      'test/browser/spec/ol/render/webgl/bufferUtil.test.js',
      'test/browser/spec/ol/render/webgl/encodeUtil.test.js',
      'test/browser/spec/ol/render/webgl/shaderbuilder.test.js',
      'test/browser/spec/ol/render/webgl/style.test.js',
      'test/browser/spec/ol/renderer/webgl/Layer.test.js',
      'test/browser/spec/ol/renderer/webgl/TileLayer.test.js',
      'test/browser/spec/ol/reproj/reproj.test.js',
      'test/browser/spec/ol/reproj/triangulation.test.js',
      'test/browser/spec/ol/resolutionconstraint.test.js',
      'test/browser/spec/ol/rotationconstraint.test.js',
      'test/browser/spec/ol/size.test.js',
      'test/browser/spec/ol/source.test.js',
      'test/browser/spec/ol/source/IIIF.test.js',
      'test/browser/spec/ol/source/Image.test.js',
      'test/browser/spec/ol/source/StadiaMaps.test.js',
      'test/browser/spec/ol/source/TileArcGISRest.test.js',
      'test/browser/spec/ol/source/TileWMS.test.js',
      'test/browser/spec/ol/source/UrlTile.test.js',
      'test/browser/spec/ol/source/Zoomify.test.js',
      'test/browser/spec/ol/source/cartodb.test.js',
      'test/browser/spec/ol/source/cluster.test.js',
      'test/browser/spec/ol/string.test.js',
      'test/browser/spec/ol/style/fill.test.js',
      'test/browser/spec/ol/style/iconimagecache.test.js',
      'test/browser/spec/ol/style/stroke.test.js',
      'test/browser/spec/ol/style/style.test.js',
      'test/browser/spec/ol/style/text.test.js',
      'test/browser/spec/ol/tilecoord.test.js',
      'test/browser/spec/ol/tilerange.test.js',
      'test/browser/spec/ol/tileurlfunction.test.js',
      'test/browser/spec/ol/transform.test.js',
      'test/browser/spec/ol/uri.test.js',
      'test/browser/spec/ol/worker/webgl.test.js',
    ],
    globals: true,
    setupFiles: [path.resolve(dir, 'vitest.setup.js')],
    browser: {
      enabled: true,
      provider: playwright(),
      headless: true,
      instances: [{browser: 'chromium'}],
    },
  },
});
