import {playwright} from '@vitest/browser-playwright';
import path from 'path';
import {fileURLToPath} from 'url';
import {defineConfig} from 'vitest/config';
import olFixtures from './vite-plugin-ol-fixtures.mjs';
import olWorker from './vite-plugin-ol-worker.mjs';

const dir = path.dirname(fileURLToPath(import.meta.url));

// Runs a few representative specs while the migration off Karma is in progress.
export default defineConfig({
  plugins: [olWorker(), olFixtures()],
  test: {
    include: [
      'test/browser/spec/ol/DataTile.test.js',
      'test/browser/spec/ol/Map.test.js',
      'test/browser/spec/ol/MapBrowserEvent.test.js',
      'test/browser/spec/ol/Tile.test.js',
      'test/browser/spec/ol/View.test.js',
      'test/browser/spec/ol/color.test.js',
      'test/browser/spec/ol/colorlike.test.js',
      'test/browser/spec/ol/control/attribution.test.js',
      'test/browser/spec/ol/control/control.test.js',
      'test/browser/spec/ol/control/fullscreen.test.js',
      'test/browser/spec/ol/control/mouseposition.test.js',
      'test/browser/spec/ol/control/overviewmap.test.js',
      'test/browser/spec/ol/control/rotate.test.js',
      'test/browser/spec/ol/control/zoom.test.js',
      'test/browser/spec/ol/control/scaleline.test.js',
      'test/browser/spec/ol/control/zoomslider.test.js',
      'test/browser/spec/ol/control/zoomtoextent.test.js',
      'test/browser/spec/ol/dom/dom.test.js',
      'test/browser/spec/ol/expr/cpu.test.js',
      'test/browser/spec/ol/expr/expression.test.js',
      'test/browser/spec/ol/expr/gpu.test.js',
      'test/browser/spec/ol/featureloader.test.js',
      'test/browser/spec/ol/format/gml.test.js',
      'test/browser/spec/ol/format/gpx.test.js',
      'test/browser/spec/ol/format/igc.test.js',
      'test/browser/spec/ol/format/iiif.test.js',
      'test/browser/spec/ol/format/kml.test.js',
      'test/browser/spec/ol/format/mvt.test.js',
      'test/browser/spec/ol/format/osmxml.test.js',
      'test/browser/spec/ol/format/ows.test.js',
      'test/browser/spec/ol/format/wfs.test.js',
      'test/browser/spec/ol/format/wmscapabilities.test.js',
      'test/browser/spec/ol/format/wmsgetfeatureinfo.test.js',
      'test/browser/spec/ol/format/wmtscapabilities.test.js',
      'test/browser/spec/ol/format/xsd.test.js',
      'test/browser/spec/ol/geolocation.test.js',
      'test/browser/spec/ol/graticule.test.js',
      'test/browser/spec/ol/image.test.js',
      'test/browser/spec/ol/imagetile.test.js',
      'test/browser/spec/ol/net.test.js',
      'test/browser/spec/ol/interaction/DragBox.test.js',
      'test/browser/spec/ol/interaction/Draw.test.js',
      'test/browser/spec/ol/interaction/Pointer.test.js',
      'test/browser/spec/ol/interaction/dblclickdragzoom.test.js',
      'test/browser/spec/ol/interaction/draganddrop.test.js',
      'test/browser/spec/ol/interaction/dragrotateandzoom.test.js',
      'test/browser/spec/ol/interaction/interaction.test.js',
      'test/browser/spec/ol/interaction/extent.test.js',
      'test/browser/spec/ol/interaction/dragzoom.test.js',
      'test/browser/spec/ol/interaction/modify.test.js',
      'test/browser/spec/ol/interaction/keyboardpan.test.js',
      'test/browser/spec/ol/interaction/keyboardzoom.test.js',
      'test/browser/spec/ol/interaction/select.test.js',
      'test/browser/spec/ol/interaction/snap.test.js',
      'test/browser/spec/ol/interaction/translate.test.js',
      'test/browser/spec/ol/layer/Flow.test.js',
      'test/browser/spec/ol/layer/Group.test.js',
      'test/browser/spec/ol/layer/Heatmap.test.js',
      'test/browser/spec/ol/layer/WebGLTile.test.js',
      'test/browser/spec/ol/layer/WebGLVector.test.js',
      'test/browser/spec/ol/layer/WebGLVectorTile.test.js',
      'test/browser/spec/ol/layer/Image.test.js',
      'test/browser/spec/ol/layer/Layer.test.js',
      'test/browser/spec/ol/layer/Tile.test.js',
      'test/browser/spec/ol/layer/Vector.test.js',
      'test/browser/spec/ol/layer/vectorimage.test.js',
      'test/browser/spec/ol/layer/vectortile.test.js',
      'test/browser/spec/ol/loadingstrategy.test.js',
      'test/browser/spec/ol/overlay.test.js',
      'test/browser/spec/ol/proj/epsg3857.test.js',
      'test/browser/spec/ol/proj/transforms.test.js',
      'test/browser/spec/ol/render.test.js',
      'test/browser/spec/ol/render/box.test.js',
      'test/browser/spec/ol/render/canvas/executorgroup.test.js',
      'test/browser/spec/ol/render/canvas/index.test.js',
      'test/browser/spec/ol/render/canvas/hitdetect.test.js',
      'test/browser/spec/ol/render/canvas/immediate.test.js',
      'test/browser/spec/ol/render/canvas/style.test.js',
      'test/browser/spec/ol/render/canvas/textbuilder.test.js',
      'test/browser/spec/ol/render/canvas/zindexcontext.test.js',
      'test/browser/spec/ol/render/feature.test.js',
      'test/browser/spec/ol/render/webgl/MixedGeometryBatch.test.js',
      'test/browser/spec/ol/render/webgl/VectorStyleRenderer.test.js',
      'test/browser/spec/ol/render/webgl/bufferUtil.test.js',
      'test/browser/spec/ol/render/webgl/compileUtil.test.js',
      'test/browser/spec/ol/render/webgl/renderinstructions.test.js',
      'test/browser/spec/ol/render/webgl/encodeUtil.test.js',
      'test/browser/spec/ol/render/webgl/shaderbuilder.test.js',
      'test/browser/spec/ol/render/webgl/style.test.js',
      'test/browser/spec/ol/renderer/canvas/ImageLayer.test.js',
      'test/browser/spec/ol/renderer/canvas/Layer.test.js',
      'test/browser/spec/ol/renderer/canvas/TileLayer.test.js',
      'test/browser/spec/ol/renderer/canvas/VectorLayer.test.js',
      'test/browser/spec/ol/renderer/canvas/vectorimage.test.js',
      'test/browser/spec/ol/renderer/canvas/vectortilelayer.test.js',
      'test/browser/spec/ol/renderer/layer.test.js',
      'test/browser/spec/ol/renderer/vector.test.js',
      'test/browser/spec/ol/renderer/webgl/Layer.test.js',
      'test/browser/spec/ol/renderer/webgl/PointsLayer.test.js',
      'test/browser/spec/ol/renderer/webgl/VectorLayer.test.js',
      'test/browser/spec/ol/renderer/webgl/VectorTileLayer.test.js',
      'test/browser/spec/ol/renderer/webgl/TileLayer.test.js',
      'test/browser/spec/ol/reproj/reproj.test.js',
      'test/browser/spec/ol/reproj/tile.test.js',
      'test/browser/spec/ol/reproj/triangulation.test.js',
      'test/browser/spec/ol/resolutionconstraint.test.js',
      'test/browser/spec/ol/rotationconstraint.test.js',
      'test/browser/spec/ol/size.test.js',
      'test/browser/spec/ol/source.test.js',
      'test/browser/spec/ol/source/BingMaps.test.js',
      'test/browser/spec/ol/source/DataTile.test.js',
      'test/browser/spec/ol/source/GeoZarr.test.js',
      'test/browser/spec/ol/source/IIIF.test.js',
      'test/browser/spec/ol/source/Image.test.js',
      'test/browser/spec/ol/source/ImageArcGISRest.test.js',
      'test/browser/spec/ol/source/ImageWMS.test.js',
      'test/browser/spec/ol/source/ImageMapGuide.test.js',
      'test/browser/spec/ol/source/ImageStatic.test.js',
      'test/browser/spec/ol/source/OGCMap.test.js',
      'test/browser/spec/ol/source/Source.test.js',
      'test/browser/spec/ol/source/StadiaMaps.test.js',
      'test/browser/spec/ol/source/Tile.test.js',
      'test/browser/spec/ol/source/TileArcGISRest.test.js',
      'test/browser/spec/ol/source/TileImage.test.js',
      'test/browser/spec/ol/source/TileJSON.test.js',
      'test/browser/spec/ol/source/TileWMS.test.js',
      'test/browser/spec/ol/source/UrlTile.test.js',
      'test/browser/spec/ol/source/VectorTile.test.js',
      'test/browser/spec/ol/source/WMTS.test.js',
      'test/browser/spec/ol/source/XYZ.test.js',
      'test/browser/spec/ol/source/Zoomify.test.js',
      'test/browser/spec/ol/source/cartodb.test.js',
      'test/browser/spec/ol/source/cluster.test.js',
      'test/browser/spec/ol/source/mapserver.test.js',
      'test/browser/spec/ol/source/raster.test.js',
      'test/browser/spec/ol/source/utfgrid.test.js',
      'test/browser/spec/ol/source/vector.test.js',
      'test/browser/spec/ol/sphere.test.js',
      'test/browser/spec/ol/string.test.js',
      'test/browser/spec/ol/style/RegularShape.test.js',
      'test/browser/spec/ol/style/fill.test.js',
      'test/browser/spec/ol/style/iconimagecache.test.js',
      'test/browser/spec/ol/style/stroke.test.js',
      'test/browser/spec/ol/style/style.test.js',
      'test/browser/spec/ol/style/text.test.js',
      'test/browser/spec/ol/tilecoord.test.js',
      'test/browser/spec/ol/tilegrid/wmts.test.js',
      'test/browser/spec/ol/tilequeue.test.js',
      'test/browser/spec/ol/tilerange.test.js',
      'test/browser/spec/ol/tileurlfunction.test.js',
      'test/browser/spec/ol/transform.test.js',
      'test/browser/spec/ol/uri.test.js',
      'test/browser/spec/ol/vectorrendertile.test.js',
      'test/browser/spec/ol/vectortile.test.js',
      'test/browser/spec/ol/webgl/TileGeometry.test.js',
      'test/browser/spec/ol/webgl/TileTexture.test.js',
      'test/browser/spec/ol/webgl/buffer.test.js',
      'test/browser/spec/ol/webgl/helper.test.js',
      'test/browser/spec/ol/webgl/rendertarget.test.js',
      'test/browser/spec/ol/worker/webgl.test.js',
    ],
    globals: true,
    setupFiles: [path.resolve(dir, 'vitest.setup.js')],
    browser: {
      enabled: true,
      provider: playwright(),
      headless: true,
      instances: [{browser: 'chromium'}],
    },
  },
});
